default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  username: katemrrr
  password: 123456
  host: localhost

development:
  <<: *default
  database: new_page_dev

test:
  <<: *default
  database: new_page_test
